name: security-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check

  checkov-terraform:
    name: Checkov Scan - Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov - Terraform
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          soft_fail: true
          output_format: cli

  checkov-kubernetes:
    name: Checkov Scan - Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov - Kubernetes
        uses: bridgecrewio/checkov-action@master
        with:
          directory: clusters
          framework: kubernetes
          soft_fail: true
          output_format: cli

  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # needed to upload SARIF to Code Scanning
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install --upgrade semgrep

      - name: Run Semgrep (OSS rules)
        # advisory like Checkov; remove 'continue-on-error' to make it blocking
        continue-on-error: true
        run: |
          semgrep scan \
            --config p/ci \
            --config p/python \
            --config p/terraform \
            --config p/kubernetes \
            --config p/docker \
            --config p/github-actions \
            --sarif > semgrep.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif